### ISSUE TITLE
Missing implementation of `Base.peek(::TruncatedIO, ::Type{UInt8})::UInt8`

### ISSUE THREAD

**Issue by nhz2** [reallyasi9/TruncatedStreams.jl#5]
This is needed for `peek(x, Char)` to work.

```julia-repl
julia> x = FixedLengthIO(IOBuffer(b"🐢"),length(b"🐢"));

julia> peek(x, Char)
ERROR: ArgumentError: Base.GenericIOBuffer{Base.CodeUnits{UInt8, String}} not marked
Stacktrace:
 [1] reset
   @ ./io.jl:1266 [inlined]
 [2] reset(s::FixedLengthIO{Base.GenericIOBuffer{Base.CodeUnits{UInt8, String}}})
   @ TruncatedStreams ~/juliadev/TruncatedStreams/src/fixedlengthio.jl:123
 [3] peek(s::FixedLengthIO{Base.GenericIOBuffer{Base.CodeUnits{UInt8, String}}}, ::Type{Char})
   @ Base ./io.jl:331
 [4] top-level scope
   @ REPL[6]:1
```

**Comment by reallyasi9** [comment]
Peeking into `SentinelIO` is tricky:

```julia
io = IOBuffer(collect(0x00:0x0f))
sentinel = [0x07, 0x08, 0x09]
sio = SentinelIO(io, sentinel)

peek(sio, UInt64) # what should happen?
```
By design, `sio` will not read more bytes than it has to from `io`, meaning it only buffers the next `length(sentinel)` bytes. It can't presume to peek the additional bytes from the wrapped IO because the byte boundaries start to get weird. It can't presume that the wrapped stream implements `mark` and `reset`, either.

The implementation in https://github.com/reallyasi9/TruncatedStreams.jl/tree/5-missing-implementation-of-basepeektruncatedio-typeuint8uint8 will throw if at EOF or if the type being peeked is longer than the sentinel. If the peek could be reading into the sentinel with a partial read, the code issues a warning, though I may revisit that in the future.

**Comment by nhz2** [comment]
Trying to peek after the end of the stream should throw an `EOFError`. I think `IO` subtypes are only supposed to implement `peek` for `Type{UInt8}`, the other types should work using the fallbacks for generic `IO`. Trying to implement `peek` for a general `Type` will cause method ambiguities.
