### ISSUE TITLE
Can `TruncatedIO` be read only?

### ISSUE THREAD

**Issue by nhz2** [reallyasi9/TruncatedStreams.jl#9]
Is there any utility in writing to a `TruncatedIO`? If not I think it would be cleaner to make it a read-only IO type.

One of my biggest gripes about `TranscodingStreams.TranscodingStream` is that it has one type for both reading and writing. This leads to easy to make coding errors, and really hurts performance in some situations: https://github.com/JuliaIO/BufferedStreams.jl/issues/62#issuecomment-1156343485

**Comment by reallyasi9** [comment]
I don't really know. I can imagine a stream that truncates on write: when a certain number of bytes is reached, or when a certain sentinel is sent, the stream "closes" by throwing `EOFError` on any additional write attempts. I can also imagine an empty stream that you can write all you want to it, but that reads from it will truncate at some point--I don't think it's common to have a half-duplex stream that closes the read side early, but I won't judge.

What is the use-case here? Would it be more reasonable to have separate structs for simplex and duplex IO? Like a `TruncatedSource`, `TruncatedSink`, and `TruncatedIO`, so that users can pick what they want to use?

**Comment by nhz2** [comment]
It makes sense for them to be separate structs. For reading files from ZIP or TAR archives I'd think only `TruncatedSource` is needed.

The current implementation can be slightly confusing. For example, if I do:
```julia
io = IOBuffer(collect(0x00:0x05); read=true, write=true);
fio = FixedLengthIO(io, 10);
read(fio)
write(fio, 0x06:0xff)
eof(fio)
```
I get `true` even though I haven't read all 10 bytes yet.

**Comment by reallyasi9** [comment]
The issue you describe is a weirdness about `IOBuffer`, because the same thing happens without the `FixedLengthIO`:
```julia
julia> io = IOBuffer(collect(0x00:0x05); read=true, write=true);

julia> read(io)
6-element Vector{UInt8}:
 0x00
 0x01
 0x02
 0x03
 0x04
 0x05

julia> write(io, 0x06:0x0f)
10

julia> eof(io)
true
```
The reason is because `IOBuffer` shares the read and write pointer unless you create it with `append=true`, in which case it always writes to the end of the buffer:
```julia
julia> io.ptr
17

julia> io2 = IOBuffer(collect(0x00:0x05); read=true, write=true, append=true);

julia> read(io2)
6-element Vector{UInt8}:
 0x00
 0x01
 0x02
 0x03
 0x04
 0x05

julia> write(io2, 0x06:0x0f)
10

julia> eof(io2)
false

julia> io2.ptr
7
```
See, for example, https://github.com/JuliaLang/julia/blob/7d341eac799ffaa7dfbb62eaf670ab24de0e1a81/base/iobuffer.jl#L521.

My intention is that `eof(fio) == true` means any attempt to read from `fio` will fail (return nothing). In my opinion, it's `IOBuffer` that is doing the weird thing here.

But this does support separating reading and writing into different types. Do you want to take a stab at it?

**Comment by nhz2** [comment]
Okay, from that perspective the current behavior makes sense.

**Comment by reallyasi9** [comment]
On second thought, I think you're right. If the users need a stream that is both read-truncated and writable, we can revisit this decision, but it was getting very complicated to work out how to implement the sentinel streams in a coherent way.
